### ISSUE TITLE
Include function arguments in function name

### ISSUE THREAD

**Issue by BFergerson** [CodeBrig/Arthur#30]
There are currently no tests for [StructureNaming](https://github.com/CodeBrig/Arthur/blob/master/src/main/groovy/com/codebrig/arthur/observe/structure/StructureNaming.groovy) based classes. This means that a lot of function names are going to be returned incorrectly.

The goal here would be to start with testing [JavaNaming](https://github.com/CodeBrig/Arthur/blob/master/src/main/groovy/com/codebrig/arthur/observe/structure/naming/JavaNaming.groovy) with a simple function `functionName(int var)` and confirming that works. Then moving on to more complex function names (var args, generics, etc). 

The JavaNaming class is also unnecessarily redundant so if you see something that looks like it could be refactored then it's likely a good idea to go for it.

**Comment by chess-equality** [comment]
@BFergerson I am working on this next.

**Comment by BFergerson** [comment]
@chess-equality, I think a good pattern here would be like `Functions.java` and related files (Functions.go, etc). Basically, have a folder `same/naming/functions` (as opposed to `same/functions` for the FunctionFilter related tests) and in that folder have `FunctionNames.java` (FileNames.go, etc).

These functions would all be empty like:
```java
public void functionName(int var) {}
```

and the tests that assert on their names would simply assert that a function with that name is found, like:
```groovy
def functionFilter = new FunctionFilter()
def nameFilter = new NameFilter("functionName(int var)")
MultiFilter.matchAll(functionFilter, nameFilter)
```

That's basically how I'm imagining how this should work. Let me know if that all makes sense.

**Comment by chess-equality** [comment]
@BFergerson I would like to request if you could check on my initial attempt in above commit, please. Thank you.

**Comment by BFergerson** [comment]
@chess-equality, nice work. Added some comments about formatting. Other than that you're right on target.

**Comment by chess-equality** [comment]
@BFergerson I am encountering a Babelfish exception on Python variadic arguments:

```
def function5(a, *param):
    print "variadicArg"
```

```
Vector(driver failure: Traceback (most recent call last):
  File "/opt/driver/bin/.local/lib/python3.6/site-packages/python_driver/requestprocessor.py", line 155, in process_request
    ast = AstImprover(code, orig_ast).parse()
  File "/opt/driver/bin/.local/lib/python3.6/site-packages/python_driver/astimprove.py", line 39, in parse
    res = self.visit(self._astdict, root=True)
  File "/opt/driver/bin/.local/lib/python3.6/site-packages/python_driver/astimprove.py", line 66, in visit
    visit_result = meth(node)
  File "/opt/driver/bin/.local/lib/python3.6/site-packages/python_driver/astimprove.py", line 264, in visit_other
    node[field] = meth(child)
  File "/opt/driver/bin/.local/lib/python3.6/site-packages/python_driver/astimprove.py", line 271, in visit_other_field
    return [self.visit(x) for x in node]
  File "/opt/driver/bin/.local/lib/python3.6/site-packages/python_driver/astimprove.py", line 271, in <listcomp>
    return [self.visit(x) for x in node]
  File "/opt/driver/bin/.local/lib/python3.6/site-packages/python_driver/astimprove.py", line 66, in visit
    visit_result = meth(node)
  File "/opt/driver/bin/.local/lib/python3.6/site-packages/python_driver/astimprove.py", line 264, in visit_other
    node[field] = meth(child)
  File "/opt/driver/bin/.local/lib/python3.6/site-packages/python_driver/astimprove.py", line 269, in visit_other_field
    return self.visit(node)
  File "/opt/driver/bin/.local/lib/python3.6/site-packages/python_driver/astimprove.py", line 66, in visit
    visit_result = meth(node)
  File "/opt/driver/bin/.local/lib/python3.6/site-packages/python_driver/astimprove.py", line 242, in visit_arguments
    vararg["ast_type"] = "vararg"
TypeError: 'str' object does not support item assignment
)
```

Above happens after the call to `client.parse()`. I also tried the new Babelfish release v2.14.0 but stil the same. Latest for `bblfsh-client` is still v1.11.0.

**Comment by chess-equality** [comment]
@BFergerson Above exception is not encountered on keyword arguments.

```
def function6(a, **param):
    print "keywordArgs"
```

**Comment by chess-equality** [comment]
@BFergerson Another exception encountered on function annotations:

```
def function8(param: 'int'):
    print "functionAnnotation"
```

```
ParseResponse(FATAL,Vector(syntax error: Errors produced trying to get an AST for both Python versions
------ Python2 errors:
[b'Traceback (most recent call last):\n  File "<string>", line 1, in <module>\n  File "/opt/driver/bin/.local/lib/python3.6/site-packages/pydetector/ast2dict.py", line 19, in ast2dict\n    return visitor.parse()\n  File "/opt/driver/bin/.local/lib/python3.6/site-packages/pydetector/ast2dict.py", line 45, in parse\n    tree = ast.parse(self.codestr, mode=\'exec\')\n  File "/usr/lib/python2.7/ast.py", line 37, in parse\n    return compile(source, filename, mode, PyCF_ONLY_AST)\n  File "<unknown>", line 22\n    def function8(param: \'int\'):\n                       ^\nSyntaxError: invalid syntax\n']
------ Python3 errors:
['Traceback (most recent call last):\n  File "/opt/driver/bin/.local/lib/python3.6/site-packages/pydetector/ast_checks.py", line 53, in check_ast\n    current_ast = ast2dict(code)\n  File "/opt/driver/bin/.local/lib/python3.6/site-packages/pydetector/ast2dict.py", line 19, in ast2dict\n    return visitor.parse()\n  File "/opt/driver/bin/.local/lib/python3.6/site-packages/pydetector/ast2dict.py", line 45, in parse\n    tree = ast.parse(self.codestr, mode=\'exec\')\n  File "/usr/local/lib/python3.6/ast.py", line 35, in parse\n    return compile(source, filename, mode, PyCF_ONLY_AST)\n  File "<unknown>", line 2\n    print ""\n           ^\nSyntaxError: Missing parentheses in call to \'print\'. Did you mean print("")?\n']),Some(Duration(0,24164502)),None,python,)
```

**Comment by BFergerson** [comment]
@chess-equality, when you encounter bugs with Babelfish please open a ticket on the appropriate driver. I have an issue with the Java driver open [here](https://github.com/bblfsh/java-driver/issues/100).

As long as we're opening bugs and tracking them I'm okay with you skipping/commenting out anything that's not currently working. Just make sure to include a link to the issue with the commented code.

**Comment by chess-equality** [comment]
@BFergerson I have opened two issues with the Babelfish Python driver:

[Exception in variadic arguments](https://github.com/bblfsh/python-driver/issues/199)
[Exception in function annotations](https://github.com/bblfsh/python-driver/issues/200)
