### ISSUE TITLE
Tests for literals

### ISSUE THREAD

**Issue by BFergerson** [CodeBrig/Arthur#32]
The purpose of this ticket is to ensure [StructureLiteral](https://github.com/CodeBrig/Arthur/blob/master/src/main/groovy/com/codebrig/arthur/observe/structure/StructureLiteral.groovy) and its descendants properly handle the more complex of literal types.

Below I have some for Java. I doubt these are handled correctly. Tests will need to be made to show that Arthur handles them correctly. Ideally, some complex examples from other supported languages should be found and tests added for them too.

**Comment by BFergerson** [comment]
Java:
-1.2e55
9.234d
0xFFFFFFFFFFFFL

**Comment by chess-equality** [comment]
@BFergerson I'm working on this next.

**Comment by chess-equality** [comment]
@BFergerson I have pushed my initial implementation in above commit, I would like to request if you could please review it. Thank you.

**Comment by BFergerson** [comment]
@chess-equality, that's pretty close. I started adding my modifications today. I'll finish and push tomorrow. If you need something to do in the mean-time, look at the other tickets in this milestone.
