### ISSUE TITLE
Add Bash language

### ISSUE THREAD

**Issue by BFergerson** [CodeBrig/Arthur#38]
- [ ] Add to SourceLanguage
- [ ] Implement Naming
- [ ] Implement Literal
- [ ] Write tests

**Comment by chess-equality** [comment]
@BFergerson When the method [`BashNaming.getNodeName()`](https://github.com/chess-equality/Arthur/blob/feature/issue-38/Add-bash-language/src/main/groovy/com/codebrig/arthur/observe/structure/naming/BashNaming.groovy#L26) is called, it throws `StackOverflowError`. Any ideas?

**Comment by BFergerson** [comment]
@chess-equality, should have a fix here https://github.com/chess-equality/Arthur/pull/7. I should have responded earlier but I thought you were dealing with an issue I faced back when I tried to implement Bash support. I can't remember what the issue was but the issue you brought up doesn't seem to be it. Please continue working on this when you can :).

**Comment by chess-equality** [comment]
@BFergerson Thanks, will merge it after #40 which should be finished this weekend, only the literals remain.
