### ISSUE TITLE
Add C++ language

### ISSUE THREAD

**Issue by BFergerson** [CodeBrig/Arthur#40]
- [ ] Add to SourceLanguage
- [ ] Implement Naming
- [ ] Implement Literal
- [ ] Write tests

**Comment by chess-equality** [comment]
@BFergerson I'm working on this next.

**Comment by chess-equality** [comment]
@BFergerson I am getting the following error:

`unexpected error: runtime failure: missing driver for language "cplusplus"`

Also encountered with v2.14.0 Babelfish driver.

**Comment by BFergerson** [comment]
@chess-equality, I'm not running into that issue locally or on Travis-CI (https://travis-ci.com/CodeBrig/Arthur/builds/120998896).

Make sure you're using the image `bblfsh/bblfshd:v2.14.0-drivers` and not `bblfsh/bblfshd:v2.14.0`. The former comes with all the language drivers pre-installed.

**Comment by BFergerson** [comment]
Nevermind my previous message. I'm getting this error too.

**Comment by chess-equality** [comment]
Search turns up nothing, also no GitHub issue references found.
