### ISSUE TITLE
Update StructureFilters to use semantic roles in determing predicate

### ISSUE THREAD

**Issue by BFergerson** [CodeBrig/Arthur#50]
Currently, the [StructureFilter](https://github.com/CodeBrig/Arthur/blob/master/src/main/groovy/com/codebrig/arthur/observe/structure/StructureFilter.groovy) sub-classes all use the `internalType`/`token` in determining if the predicate passes or fails. An example of this would be:
```java
class FunctionFilter extends StructureFilter<FunctionFilter, Void> {

    private static final Set<String> functionTypes = new HashSet<>()
    static {
        functionTypes.add("def") //ruby
        functionTypes.add("FuncDecl") //go
        functionTypes.add("MethodDeclaration") //java
        functionTypes.add("FunctionDeclaration") //js
        functionTypes.add("Stmt_Function") //php
        functionTypes.add("FunctionDef") //python
    }

    @Override
    boolean evaluate(SourceNode node) {
        return node != null && node.internalType in functionTypes
    }
}
```

This results in checking for a specific type per-language. These need to be re-written so the semantic roles are used instead.

**Comment by chess-equality** [comment]
@BFergerson Working on this.

**Comment by chess-equality** [comment]
@BFergerson In my initial try in above commit (for Java, Go, and JavaScript only), I return `true` only when role is a function and function token is not empty. This results with returned internal types of `SimpleName`, `Ident`, and `Identifier` for Java, Go, and JavaScript, respectively. In the `*Naming.groovy` classes I am just returning the token name but I am not sure if this is the best approach.

**Comment by BFergerson** [comment]
@chess-equality, I definitely could have provided more information here so thanks for reaching out.

I've shown an example of how the FunctionFilter could be made more language agnostic here:
 - https://github.com/CodeBrig/Arthur/commit/03889011f45de71fbc8c64419953b1c616d53750

Notice that I'm not using the `internalType`/`token` to determine if the `evaluate()` method passes.
I use a combination of the `MultiFilter` and `RoleFilter` to say:
 - must have `DECLARATION`
 - must have `FUNCTION`
 - cannot have `ARGUMENT`, `RETURN`, `INCOMPLETE`, `BODY` (gets rid of the false positives you're getting)

This is how all the filters should be. If it truely turns out you can't determine the difference based on roles then you can fall back to `internalType`/`token` but I'm not expecting that to be the case anywhere.

**Comment by chess-equality** [comment]
@BFergerson Thanks it helped a lot, please keep 'em coming! I'd do some more digging myself to see these types of patterns.

> I imagine realizing that is what actually made you reach out :P.

Yeah I felt I was missing something :-)
