### ISSUE TITLE
Make the tests more language-agnostic

### ISSUE THREAD

**Issue by BFergerson** [CodeBrig/Arthur#51]
When I first started making the tests I just copied one test to the next. This resulted in many tests which look almost the same but scans a different file. I started merging tests down so they look like this:
```groovy
@Test
void equalOperator_Java() {
    assertEqualOperatorPresent(new File("src/test/resources/same/operators/Operators.java"),
            "Operators.")
}

@Test
void equalOperator_Javascript() {
    assertEqualOperatorPresent(new File("src/test/resources/same/operators/Operators.js"))
}

@Test
void equalOperator_Php() {
    assertEqualOperatorPresent(new File("src/test/resources/same/operators/Operators.php"))
}
```

This process needs to be repeated for the remaining classes and used going forward. The only reason it isn't just something like:
```groovy
SourceLanguages.values().each {
    assertEqualOperatorPresent(new File("src/test/resources/same/operators/Operators." + it.getExtension()))
}
```

would be because sometimes the tests assert slightly different naming. For example, Java expects names to be fully qualified. If it can be made better, go for it.

**Comment by chess-equality** [comment]
@BFergerson I will be working on this next.
