### ISSUE TITLE
Replace println with log.info

### ISSUE THREAD

**Issue by BFergerson** [CodeBrig/Arthur#53]
Replace any output to stdout with log.info()

**Comment by chess-equality** [comment]
Should logback be used?

**Comment by BFergerson** [comment]
I chose SLF4J. Please follow this pattern for naming (log): https://github.com/CodeBrig/Arthur/blob/b73d95330b2969996fc3dfbc4ba1a0ae48bafacf/src/main/groovy/com/codebrig/arthur/observe/structure/literal/GoLiteral.groovy#L17

**Comment by chess-equality** [comment]
@BFergerson I would like to request to be granted access to push branches and create PRs. Thanks.

**Comment by BFergerson** [comment]
@chess-equality, you won't be able to create branches on this project but you can on your fork. I would ask that for now you work off your fork and submit your pull requests here.

You should start with branching off this branch: https://github.com/chess-equality/Arthur/tree/v0.4

**Comment by BFergerson** [comment]
@chess-equality, also this request is only for the main code. Please don't replace any `echo ""` or `System.out.println` in the tests. Those are okay.

**Comment by chess-equality** [comment]
@BFergerson 

> I would ask that for now you work off your fork...

Ok.

> also this request is only for the main code. Please don't replace any echo "" or System.out.println in the tests. Those are okay.

Yes I have also noted of those; thanks for clarifying.

**Comment by chess-equality** [comment]
@BFergerson Please check above PR.
